import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/theme-provider";
import Navbar from "@/components/Navbar";
import { Amiri, Noto_Nastaliq_Urdu } from "next/font/google";
import { ScrollArea } from "@/components/ui/scroll-area";
import GradualBlurMemo from "@/components/ui/GradualBlur";
import Footer from "@/components/Footer";

const amiri = Amiri({
  subsets: ["arabic"],
  variable: "--font-amiri",
  weight: ["400", "700"],
});
const nastaliq = Noto_Nastaliq_Urdu({
  subsets: ["arabic"],
  variable: "--font-nastaliq",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ar"
      dir="rtl"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        amiri.variable,
        nastaliq.variable,
        "font-sans",
      )}
    >
      <body dir="rtl" className="relative min-h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <ScrollArea className="h-screen w-full">
            {children}
            <Footer />
          </ScrollArea>
          <GradualBlurMemo
            target="parent"
            position="bottom"
            height="7rem"
            strength={2}
            divCount={5}
            curve="bezier"
            exponential
            opacity={1}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
